export const projects = [
  {
    slug: "blue-archive-api",
    name: "Blue Archive API",
    body: "This is an open source API providing character information about the Blue Archive.",
    description: "An open source API built to provide comprehensive character information for the popular game Blue Archive. The data is carefully sourced from public domains and structured to be easily consumable by other developers building fan-made applications, wikis, or tools.",
    useCase: "Ideal for developers creating Discord bots, companion web applications, or data analysis tools related to Blue Archive characters.",
    techStack: ["Node.js", "Express", "MongoDB", "RESTful API Concept"],
    link: "https://bluearchive.com",
  },
  {
    slug: "nextjs-14-extension-snippets",
    name: "Next.js 14 Extension Snippets",
    body: "This is a collection of useful code snippets to speed up development in Next.js 14.",
    description: "A highly specific collection of VS Code snippets tailored for Next.js 14 (and 13) App Router architectures. It drastically reduces boilerplate coding times by providing quick-access commands to generate Server Components, Client Components, Actions, and metadata structures.",
    useCase: "Helps frontend developers increase productivity and maintain consistent coding standards while working in Next.js modern projects.",
    techStack: ["VS Code Extension API", "JSON", "Regex"],
    link: "https://nextjs.org",
  },
  {
    slug: "gallery-blue-archive",
    name: "Gallery Blue Archive",
    body: "Platform providing comprehensive information about characters in Blue Archive.",
    description: "A visually appealing web platform serving as an encyclopedia and gallery for Blue Archive characters. Users can smoothly navigate through the roster, view high-quality character arts, and read detailed lore, stats, and meta information.",
    useCase: "Designed for players who want a quick, beautiful, and mobile-friendly way to explore game characters without sifting through heavy wiki pages.",
    techStack: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
    link: "https://example.com/gallery",
  },
  {
    slug: "felilearn",
    name: "FeliLearn",
    body: "AI-based web app that helps identify and learn cat (Felidae) species using CNN.",
    description: "FeliLearn merges educational technology with artificial intelligence. By utilizing a Convolutional Neural Network (CNN) based image classification model, users can upload photos of various feline species and instantly get identification alongside educational facts about the species.",
    useCase: "Useful for biology students, wildlife enthusiasts, and educators looking to make learning about Felidae interactive and engaging.",
    techStack: ["Python", "TensorFlow", "React", "FastAPI"],
    link: "https://example.com/felilearn",
  },
  {
    slug: "khass-hair-style",
    name: "Khass Hair Style",
    body: "App that recommends hairstyles tailored to your face shape using advanced tech.",
    description: "Khavi (Khass Hair Style) solves the dilemma of choosing a new haircut. By analyzing the user's face shape via camera input, the system recommends the most flattering hairstyles. It also features a community forum to discuss beauty and hair care tips.",
    useCase: "A lifestyle app for individuals looking for personalized styling choices and a community of beauty enthusiasts.",
    techStack: ["React Native", "OpenCV", "Node.js", "PostgreSQL"],
    link: "https://example.com/khass",
  },
  {
    slug: "galley-public-new",
    name: "Galley Public (New)",
    body: "On Working Progress 🚧",
    description: "A new public gallery project that is currently in active development. Stay tuned for exciting new features regarding image sharing and community curation.",
    useCase: "Future platform for digital artists and photographers to showcase their public portfolios.",
    techStack: ["Next.js", "TypeScript", "Prisma"],
    link: "#",
  },
];
